version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nexa_stay_db
    environment:
      POSTGRES_DB: hotelier_db
      POSTGRES_USER: hotelier_user
      POSTGRES_PASSWORD: hotelier_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  eureka-server:
    image: openjdk:17-jdk-slim
    container_name: eureka_server
    ports:
      - "8761:8761"
    volumes:
      - ./nexa-stay-backend/eureka-server/target:/app
    command: ["java", "-jar", "/app/eureka-server.jar"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: 